### ISSUE TITLE
createdAt date for product and user is giving error message

### ISSUE THREAD

**Issue by g-londhe** [saleor/saleor#10086] opened 2022-07-04 04:28 UTC
### What I'm trying to achieve
Trying to get created/createdAt date for user and product.

### Steps to reproduce the problem

I'm using following queries for 
1. Product
2. `query ProductList(
  $after: String
  $before: String
  $first: Int!
  $sortBy: ProductOrder
  $filter: ProductFilterInput
) {
  products(after: $after, before: $before first: $first, sortBy: $sortBy, filter: $filter) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      __typename
    }
    edges {
      node {
        id
        name
        slug
        updatedAt
        created
        channelListings {
          channel {
            id
            slug
          }
          id
          isPublished
          publicationDate
        }
        variants {
          id
          name
          sku
          pricing {
            onSale
            __typename
          }
          __typename
        }
        attributes {
          attribute {
            id
            slug
            name
            __typename
          }
          values {
            name
            __typename
          }
        }
        __typename
      }
    }
  }
}
`
with variables as follows
`{
  "first": 10,
  "after": "",
  "before": "",
  "filter": {
    "attributes": [
      {
        "slug": "slug-value-here",
        "values": "attribute-value-here"
      }
    ]
  },
  "sortBy": {
    "field": "NAME",
    "direction": "ASC"
  }
}`
3. Same goes for users' queries as well.

### What I expected to happen
I should get created/createdAt date in response

### Screenshots and logs

`"message": "'ChannelContext' object has no attribute 'created_at'"`

**System information**

Saleor version:
- [  ] dev (current main)
- [x] 3.2
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by maarcingebala** [comment] 2022-07-04 09:56
Can you please check this query in Saleor 3.4.9? I cannot reproduce it on this version. I believe the created/createdAt fields were fixed in these PRs:

https://github.com/saleor/saleor/pull/10073/
https://github.com/saleor/saleor/pull/9737

**Closed by maarcingebala** 2022-07-04 09:56 UTC
Labels: bug
