### ISSUE TITLE
Bug: Permissions ignored in Promotions query

### ISSUE THREAD

**Issue by supersilverlemonhaze** [saleor/saleor#16484] opened 2024-08-05 15:32 UTC
### What are you trying to achieve?

Using a token from my admin account to query promotions just like i query other protected stuff yields the "To access this path, you need one of the following permissions: MANAGE_DISCOUNTS", error. I verified through the UI that I have the permissions on my account.

### Steps to reproduce the problem

Create fresh saleor instance w version 3.20, only things i changed was i added new shipping zone and channel. Its supposed to work regardless

### What did you expect to happen?

That i can manage the discounts when i have the proper permissions ....

### Environment

Saleor version: 3.20, same w dashboard
OS and version: …

**Comment by korycins** [comment] 2024-08-07 06:50
Checked this with 3.20, and I am getting a correct results: user with manage_discounts is able to fetch promotions
![image](https://github.com/user-attachments/assets/1182142f-1c67-4724-ad1d-883abd61d253)
User without manage_discounts receives permission error:
![image](https://github.com/user-attachments/assets/7cf90d06-1172-48b8-ba0d-c213124920f3)

Make sure, that you're using a correct token, or provide more details like:
```
	me{
		userPermissions{
			code
		}
		permissionGroups{
			permissions{
				code
			}
		}
	}
```
Some screenshots, and details of what type of auth layer you're using - is it built-in one? OIDCPlugin with SSO/without SSO?

**Comment by aniav** [comment] 2024-11-29 13:56
I will close the issue for now as it seems this is actually not a bug. Feel free to reopen if it keeps happening 🙌

**Closed by aniav** 2024-11-29 13:56 UTC
