### ISSUE TITLE
Install on MacOS Apple M1 failed

### ISSUE THREAD

**Issue by hacker-cb** [saleor/saleor#8933] opened 2022-01-10 19:46 UTC
### What I'm trying to achieve

Just want to install on MacOS Monterey 12.1.

### Steps to reproduce the problem

1. `git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3`
2. `docker-compose build`

### What I expected to happen

No error

### Screenshots and logs

**System information**

```
=> ERROR [4/5] RUN npm install                                                                                                               40.3s
------
 > [4/5] RUN npm install:
#9 37.17
#9 37.17 > phantomjs-prebuilt@2.1.16 install /app/node_modules/phantomjs-prebuilt
#9 37.17 > node install.js
#9 37.17
#9 37.28 PhantomJS not found on PATH
#9 37.28 Unexpected platform or architecture: linux/arm64
#9 37.28 It seems there is no binary available for your platform/architecture
#9 37.28 Try to install PhantomJS globally
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/jest/node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/chokidar/node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/@storybook/addon-storyshots/node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/@jest/transform/node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/@storybook/addon-docs/node_modules/fsevents):
#9 38.98 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#9 38.98
#9 39.05 npm ERR! code ELIFECYCLE
#9 39.05 npm ERR! errno 1
#9 39.05 npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
#9 39.05 npm ERR! Exit status 1
#9 39.05 npm ERR!
#9 39.05 npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
#9 39.05 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 39.13
#9 39.13 npm ERR! A complete log of this run can be found in:
#9 39.13 npm ERR!     /root/.npm/_logs/2022-01-10T19_38_56_371Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
ERROR: Service 'storefront' failed to build : Build failed

```
Saleor version:
- [ X] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [X] MacOS Monterey 12.1 (Apple M1)
- [ ] Other

**Comment by juancarlosjr97** [comment] 2022-01-11 00:54
Same here :(... I am going to try using a codespace to run local development

**Comment by karolkielecki** [comment] 2022-01-12 12:09
Hi guys! Thanks for reporting. I've passed the issue to the team. Unfortunately, we're a bit behind on some other stuff--we have higher priorities at the moment. We'll try to reproduce the problems with `saleor-platform` as soon as possible.

**Comment by juancarlosjr97** [comment] 2022-01-12 12:30
I could not run it using codespace unfortunately

**Comment by THenry14** [comment] 2022-01-12 12:47
You can add `platform: "linux/amd64"` in docker-compose file under the service that have this problem as a workaround.

https://docs.docker.com/compose/compose-file/compose-file-v2/#platform

**Comment by haneef-photon** [comment] 2022-01-26 17:55
@hacker-cb  @juancarlosjr97 I was able to get the core & dashboard setup working. You need to clone the repository and then, important, checkout the 3.0 branches for core & dashboard before proceeding with docker build commands. Only then it will run without issues. The documentation does not talk about this important step unfortunately! I couldn't get the storefront to work as part of docker setup, so I cloned it separately, checked out latest version and ran it with saleor-platform docker setup of the core & dashboard and it worked fine.

**Comment by metouitude** [comment] 2022-02-01 17:27
The best thing i got to upcome this error is to go to the dockerfile (storefront)
and it looks like a version problem so (be sure to edit dockerfile.dev) : 
FROM node:12.22.9
WORKDIR /app
COPY package*.json ./
RUN npm update -g
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start -- --host 0.0.0.0

Then go to saleor dashbord's dockerfile.dev and do the same changes :
FROM node:12.22.9

WORKDIR /app
COPY package*.json ./
RUN npm update -g
RUN npm install
COPY . .
ARG APP_MOUNT_URI
ARG API_URI
ARG STATIC_URL
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}
ENV APP_MOUNT_URI ${APP_MOUNT_URI:-/dashboard/}
ENV STATIC_URL ${STATIC_URL:-/dashboard/}

EXPOSE 9000
CMD npm start -- --host 0.0.0.0

**Comment by SewerynPiorkowski** [comment] 2022-02-02 17:32
@metouitude not working for me :/

**Comment by malakbenr** [comment] 2022-02-05 12:37
Same issue here :(

**Comment by metouitude** [comment] 2022-02-05 12:52
> Same issue here :(

Did you tried edititng the content of dockerfiles?

**Comment by malakbenr** [comment] 2022-02-06 12:20
Yes, I edit the content of docker files but the error keeps occurring..
<img width="730" alt="Screen Shot 2022-02-06 at 1 17 13 PM" src="https://user-images.githubusercontent.com/48383170/152680410-2289a27e-a509-4fcc-b5ea-2c58c939061a.png">

**Comment by metouitude** [comment] 2022-02-06 18:43
> Yes, I edit the content of docker files but the error keeps occurring..
> 
> <img width="730" alt="Screen Shot 2022-02-06 at 1 17 13 PM" src="https://user-images.githubusercontent.com/48383170/152680410-2289a27e-a509-4fcc-b5ea-2c58c939061a.png">
> 
> 
> 
> 

Did you tried their issue resolving method ?
Here are the commands ( use docker system prune first and be sure of that you're not running other containers) :

Docker-compose stop
Docker-compose rm
Docker-compose build
Docker-compose up

**Comment by malakbenr** [comment] 2022-02-09 18:40
I did exactly as requested but I get a new issue :( 
<img width="730" alt="Screen Shot 2022-02-09 at 7 36 42 PM" src="https://user-images.githubusercontent.com/48383170/153267865-3bad3203-5683-4f9d-b616-b9d99cd526ca.png">

**Comment by THenry14** [comment] 2022-02-10 08:41
> I did exactly as requested but I get a new issue :( <img alt="Screen Shot 2022-02-09 at 7 36 42 PM" width="730" src="https://user-images.githubusercontent.com/48383170/153267865-3bad3203-5683-4f9d-b616-b9d99cd526ca.png">

@malakbenr 

Can you show your docker-compose file? It looks like you did not set platform to "linux/amd64". Some of the packages (both npm and python) may not have arm compiled versions and this might be the issue. 

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 89156e6..fc2d155 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,6 +2,7 @@ version: "2"

 services:
   api:
+    platform: "linux/amd64"
     ports:
       - 8000:8000
     build:
@@ -30,17 +31,20 @@ services:
       - DASHBOARD_URL=http://localhost:9000/

   storefront:
+    platform: "linux/amd64"
     build:
       context: ./saleor-storefront
       dockerfile: ./Dockerfile.dev
     restart: unless-stopped
     
 (...)
```

Note that you have to set the platform to at least `api`, `worker`, `dashboard` and `storefront` services ( I set it for every service though and it works, no additional changes to dockerfiles are required ). Please also note that I am using version 2.11 (pinned commit in saleor-platform repo). 

If you have any problems, try to clone **_the clean repo_** first, make the changes in docker-compose file and then try to run it. Hope that helps.

**Comment by timuric** [comment] 2022-03-03 15:27
@hacker-cb looks like it is no longer an issue on M1, could you please purge and give it a try?

**Closed** 2022-03-03 15:27 UTC
Labels: bug

**Comment by juancarlosjr97** [comment] 2022-03-29 10:29
I am still having the same issue, I cannot run it :(

**Comment by dotZak** [comment] 2022-05-06 14:11
If anyone struggles with this…

I freshly `clone`d the repository for the first time today and had the issue described in this thread.

I `cd`ed into the _react-storefront/_ directory and noticed it wasn't on the `main` branch. I did `git checkout main` and then re-ran `docker compose build` and it worked.

The reason I checked was because this was in the log…

```sh
#23 22.49 > husky install
#23 22.49
#23 22.55 fatal: not a git repository (or any of the parent directories): .git
```

**Comment by BenVN123** [comment] 2022-05-25 05:28
@dotZak This solution worked for me. Thanks!
