### ISSUE TITLE
Bug: Modify variant attributes of products with more than one variant attribute, saving leads to unexplainable form errors

### ISSUE THREAD

**Issue by genox** [saleor/saleor#13088] opened 2023-06-16 06:18 UTC
### What are you trying to achieve?

Product with 2 variant attributes fail to save with form errors (`Field is required`) after editing one of the two attribute fields.

### Steps to reproduce the problem

Using the tabular variant editor.

1. Add variants to a product with more than 1 attribute
2. Save
3. Edit one attribute
4. Save
5. Field is marked red and message `All attributes flagged as having a value required must be supplied. Error code REQUIRED on field attributes` even though there is a value present

### What did you expect to happen?

I expect save to work if fields are, in fact, containing a value.

The workaround is to re-fill all fields with new data, making me assume that the data shown in the UI is detached from the actual model state of the variants.

### Environment

Saleor SaaS

**Comment by wojteknowacki** [comment] 2023-09-20 07:53
unfortunatelly i cant reproduce it, seems like this bug is no longer present, I'm closing this for now

**Closed by wojteknowacki** 2023-09-20 07:53 UTC
Labels: bug
