### ISSUE TITLE
file urls are not valid if using S3 or GS

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#9421] opened 2022-03-28 17:52 UTC
as mentioned in here: https://github.com/saleor/saleor/pull/9332

Any file URL is parsed from the server IP even if the server isn't serving the media files

**Comment by dougli** [comment] 2022-05-06 13:12
Dupe of #8106. I'll try to have a pull request for this in the next few days.

**Comment by aniav** [comment] 2024-10-15 22:42
Relevant PRs have additional descriptions

**Closed by aniav** 2024-10-15 22:42 UTC
Labels: bug
