### ISSUE TITLE
Bug: Applications stuck in "pending" state (issue with app manifest validation and missing app management features)

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#11003] opened 2022-10-19 15:25 UTC
### What are you trying to achieve?

- tried to install the application
- due to issue with the extension manifest, application can't be installed
- now dashboard displays entries in `Ongoing installations` section
- I'm unable to remove them (there's mutation for removing only the FAILED installations, and ongoing installations cant be removed with removeApp (since app object is not created))

### Steps to reproduce the problem

1. Install app with manifest: 
```json
{
    "name": "template-examples-extensions",
    "tokenTargetUrl": "http://localhost:3000/api/register",
    "appUrl": "http://localhost:3000",
    "permissions": [],
    "id": "saleor.app",
    "version": "1.0.0",
    "webhooks": [],
    "extensions": [
        {
            "label": "X",
            "mount": "CustomerDetailsMoreActions",
            "permissions": [],
            "target": "POPUP",
            "url": "http://localhost:3000/extensions/CustomerDetailsMoreActions/POPUP/extension"
        },
        {
            "label": "X",
            "mount": "CustomerOverviewCreate",
            "permissions": [],
            "target": "POPUP",
            "url": "http://localhost:3000/extensions/CustomerOverviewCreate/POPUP/extension"
        },
        {
            "label": "X",
            "mount": "CustomerOverviewMoreActions",
            "permissions": [],
            "target": "POPUP",
            "url": "http://localhost:3000/extensions/CustomerOverviewMoreActions/POPUP/extension"
        }
    ]
}
```

2. App installation will begin, but never end
3. Enjoy spinners in the dashboard section 
![image](https://user-images.githubusercontent.com/5188636/196734023-d306c7dc-ab4d-447a-b228-4f47e6805f03.png)

The issue is caused by wrong value for the `"mount": "CustomerDetailsMoreActions"` (wrong value due to programmer error). If I change it to `CUSTOMER_DETAILS_MORE_ACTIONS ` (correct enum value), the application will install properly.

### What did you expect to happen?

- manifest should be validated before installation begin
- even if the installation is stuck for some reason, the admin should be able to remove it via dashboard

### Logs

```json
"appsInstallations": [
      {
        "status": "PENDING",
        "id": "QXBwSW5zdGFsbGF0aW9uOjIxOQ==",
        "appName": "template-examples-extensions"
      },
      {
        "status": "PENDING",
        "id": "QXBwSW5zdGFsbGF0aW9uOjIyMA==",
        "appName": "template-examples-extensions"
      }
    ]
```

```json
"data": {
    "appDeleteFailedInstallation": {
      "errors": [
        {
          "field": "id",
          "message": "Cannot delete installation with different status than failed."
        }
      ],
      "appInstallation": null
    }
  },
```

```json
{
  "data": {
    "appDelete": {
      "errors": [
        {
          "field": "id",
          "message": "Must receive a App id."
        }
      ]
    }
  },
```

### Environment

Saleor version: core v3.7.26 (Cloud instance - production)
OS and version:

**Comment by akhial** [comment] 2023-06-20 18:40
Still present on Saleor 3.13.18.

**Comment by tsanny** [comment] 2024-09-04 04:26
Hello. this issue still persists Saleor 3.19.4. Is there happened to be any PRs that fixes this?
![image](https://github.com/user-attachments/assets/9a81531d-5fc7-4713-a2d1-1ca57c027e51)

**Comment by lkostrowski** [comment] 2024-09-05 19:40
@tsanny do you use Saleor Cloud or self hosted?

**Comment by tsanny** [comment] 2024-09-06 02:08
> @tsanny do you use Saleor Cloud or self hosted?

self hosted on GCP, both Saleor and the app. Both also has https

**Comment by przlada** [comment] 2024-09-13 09:22
Hi @tsanny,
I wanted to ask about your Celery configuration in your self-hosted Saleor setup. App installation runs as a background task and requires a Celery worker to complete.
Could you please confirm if you have a Celery worker running and a Celery broker configured? If not, this might be the cause of the installation being stuck in a "pending" state.

For reference, you can find information about configuring Celery in our documentation, specifically the [CELERY_BROKER_URL](https://docs.saleor.io/setup/configuration#celery_broker_url) section. Additionally, you might find our [Saleor-platform configuration](https://github.com/saleor/saleor-platform/blob/698906d6daf37ab31dbff48689870a9948dfee82/docker-compose.yml#L48-L72) helpful, which provides an example setup using Redis as the Celery broker

**Comment by aniav** [comment] 2024-10-16 22:00
I'll close this issue for now, feel free to reopen with more details 🙌

**Closed by aniav** 2024-10-16 22:00 UTC
Labels: bug, triage
