### ISSUE TITLE
Set slug of attribute value using GraphQL

### ISSUE THREAD

**Issue by jcernik-solteq** [saleor/saleor#6019] opened 2020-08-18 07:45 UTC
### What I'm trying to achieve
I am trying to set slug/admin value of an attribute value using GraphQL.

### Steps to reproduce the problem
1. Create an attribute.
2. Insert value with name "A+"
3. Insert value with name "A++"
4. Error "ALREADY_EXISTS".
5. The same happens with "5.5 %" and "55 %"

### What I expected to happen
Both A+ and A++ are saved as possible values for the attribute.
I expect to be able to decide what the admin value will be so I can use these attribute values to represent my products with.

### Screenshots
![image](https://user-images.githubusercontent.com/69465981/90484751-e7b36a00-e136-11ea-9728-e4cb5f285093.png)

**Comment by maarcingebala** [comment] 2023-10-20 14:24
The issue is now fixed; Saleor generates unique slugs by appending numeric values to the original slug.

**Closed by maarcingebala** 2023-10-20 14:24 UTC
Labels: bug
