### ISSUE TITLE
backend saleor was unavailable after upgrading to 3.4.6 (reverted back to 3.4.3)

### ISSUE THREAD

**Issue by matteius** [saleor/saleor#10020] opened 2022-06-18 15:41 UTC
### What I'm trying to achieve
Was trying to upgraded to latest saleor from 3.4.5

### Steps to reproduce the problem
I ran the DB migrations just fine, but it seemed the graph QL API was totally unavailable, and something was causing many long running queries against the Database that would never finish on their own.

### What I expected to happen
Even despite killing the long running queries, the graph QL playground UI was reachable but it would never get a response back from saleor API (unable to connect to server).

### Screenshots and logs
![SaleorLongRunningQueries](https://user-images.githubusercontent.com/479892/174445927-32d94f34-40f0-4069-96dd-27a53973f1a3.jpg)

**Comment by matteius** [comment] 2022-06-18 15:52
I suppose though that even 3.4.5 has long running queries that never finish
![image](https://user-images.githubusercontent.com/479892/174446426-12cfd7da-8920-4562-a836-d30591cf74a9.png)

**Comment by matteius** [comment] 2022-06-18 15:55
I believe those long running queries must correlate back to a new penalty on my web.dev Best Practices score with the timeouts to /graphql

![image](https://user-images.githubusercontent.com/479892/174446545-445e3e14-cc42-4326-9b8c-3c312212ff6e.png)

**Comment by matteius** [comment] 2022-06-18 17:56
Last version that seems to run reliably for me is `3.4.3`

**Comment by matteius** [comment] 2022-06-19 01:39
Well this is quite an awful day for me after I upgraded saleor, now I cannot get back to a version that works reliably despite trying to downgrade.   I guess I didn't pay enough attention to what commits I was on that actually had a reliably working site.  The thing I notice is long running queries that get wedged for 5-10+ minutes at a time.  When I run the same query in data grip it is super fast.   I don't really understand either what these queries are about:  when its FETCH FORWARD 2000 FROM "_django_curs_139866817226496_sync_12" or CLOSE FORWARD 2000 FROM "_django_curs_139866817226496_sync_12"


I am not sure if the stack traces in the logs are from when I manually terminate the long running queries or what, but these are the only things in the logs:
```
  File "/app/saleor/core/permissions/__init__.py", line 124, in permission_required
    if isinstance(requestor, User):
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/app/saleor/graphql/context.py", line 70, in user
    return get_user(request) or AnonymousUser()
  File "/app/saleor/graphql/context.py", line 60, in get_user
    request._cached_user = cast(UserType, authenticate(request=request))
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/app/saleor/core/auth_backend.py", line 55, in authenticate
    return request.plugins.authenticate_user(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/app/saleor/core/middleware.py", line 101, in <lambda>
    lambda: _get_manager(_get_requestor_getter(request))
  File "/app/saleor/core/middleware.py", line 94, in _get_manager
    return get_plugins_manager(requestor_getter)
  File "/app/saleor/plugins/manager.py", line 1454, in get_plugins_manager
    return PluginsManager(settings.PLUGINS, requestor_getter)
  File "/app/saleor/plugins/manager.py", line 115, in __init__
    global_db_configs, channel_db_configs = self._get_db_plugin_configs()
  File "/app/saleor/plugins/manager.py", line 150, in _get_db_plugin_configs
    for db_plugin_config in qs:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/saleor/graphql/views.py", line 53, in tracing_wrapper
    return execute(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: terminating connection due to administrator command
FATAL:  server conn crashed?
SSL connection has been closed unexpectedly
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:26:ThreadPoolExecutor-0_0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/app/saleor/graphql/menu/schema.py", line 75, in resolve_menu
    return resolve_menu(
  File "/app/saleor/graphql/menu/resolvers.py", line 17, in resolve_menu
    menu = models.Menu.objects.filter(slug=slug).first()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/saleor/graphql/views.py", line 53, in tracing_wrapper
    return execute(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: SSL SYSCALL error: EOF detected
```

Its not a complete outage as the site sporadically  works making it even harder to figure out why its breaking.

**Comment by timuric** [comment] 2022-06-20 14:11
Closing this as this is a duplicate of a discussion https://github.com/saleor/saleor/discussions/10021

**Closed by timuric** 2022-06-20 14:11 UTC
Labels: bug
