### ISSUE TITLE
Vouchers/Discounts of type SPECIFIC_PRODUCT and apply_once_per_order are not applied

### ISSUE THREAD

**Issue by carlosa54** [saleor/saleor#8910] opened 2022-01-08 02:12 UTC
### What I'm trying to achieve
Add voucher to checkout/order

### Steps to reproduce the problem

1. Create a voucher discount of `VoucherType.SPECIFIC_PRODUCT` and `apply_once_per_order`
2. Add promo code to checkout
3. Complete checkout
4. The order won't have the discount created although the totals will be reflecting the discount

### What I expected to happen
- OrderDiscount record should be created
- Order `discount` property should not be "null"

### Screenshots and logs
https://github.com/saleor/saleor/blob/2221bdf61b037c660ffc2d1efa484d8efe8172f5/saleor/checkout/complete_checkout.py#L465-L482

The conditional above is preventing the creation of the `OrderDiscount` record. The comment states that `"we track it directly in the Orderline"` but I don't see that happening in the codebase.

### Questions
1. Is this an intended breaking change?
2. Do we need to handle the Vouchers with `VoucherType.SPECIFIC_PRODUCT` or `apply_once_per_order` differently?

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by timuric** [comment] 2022-03-03 12:31
_The order won't have the discount created although the totals will be reflecting the discount_
Could you please elaborate on this?

Would be great if you could use dashboard to recreate this issue and share screenshots

**Comment by carlosa54** [comment] 2022-03-06 18:19
Hi @timuric thanks for the reply

Here's a screenshot of the dashboard. I created a voucher with `VoucherType.SPECIFIC_PRODUCT` and `apply_once_per_order` for `Red Dwarf Red Paint` and applied it to the checkout. Since that won't enter the conditional from above the order discount never gets created.

> The order won't have the discount created although the totals will be reflecting the discount

<img width="870" alt="image" src="https://user-images.githubusercontent.com/4250593/156936357-7c94ff21-0c02-4418-a657-2abd4acd122c.png">

**Comment by IKarbowiak** [comment] 2023-03-08 11:54
The issue is partially fixed by `https://github.com/saleor/saleor/pull/12191`, after completing [this ticket](https://github.com/saleor/saleor/issues/12109), the discount will be properly attach to order and will be visible in the dashboard.

**Closed** 2023-03-14 13:16 UTC
Labels: bug
