### ISSUE TITLE
Bug: Products that are unavailable for purchase remain in carts

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#16156] opened 2024-06-16 23:25 UTC
### What are you trying to achieve?

When products are unpublished, they are automatically removed from user carts. However, when marked as unavailable for purchase, they remain in the carts. Users are unaware, and will try to check out.

### Steps to reproduce the problem

1. Add a product to cart
2. Mark the product as unavailable for purchase

### What did you expect to happen?

The product should be removed from the cart.

### Environment

Saleor version: 3.15.0
OS and version: Docker on Windows 10

**Comment by maarcingebala** [comment] 2024-06-18 07:27
Thanks for reporting. I guess the product will be removed from the cart anyway, but at a later step - during checkoutComplete mutation, where we re-run all the validations again. It will either be removed or an issue will be raised with a message to remove this product manually.

**Comment by divyanshu-in** [comment] 2024-08-05 09:42
@maarcingebala I'd like to work on this issue

**Comment by aniav** [comment] 2024-10-14 21:22
Hey @divyanshu-in this bug is an intended behaviour, as mentioned in the comment above. I will go ahead and close this issue.

**Closed by aniav** 2024-10-14 21:22 UTC
Labels: bug, triage, shopping
