### ISSUE TITLE
Bug: Plugin Manager not used for Shipping Prices if Taxes are disabled

### ISSUE THREAD

**Issue by supersilverlemonhaze** [saleor/saleor#16222] opened 2024-06-28 18:46 UTC
### What are you trying to achieve?

I am developing a plugin for custom shipping prices calling third party APIs implementing the method calculate_checkout_shipping of BasePlugin.

### Steps to reproduce the problem

Setup a saleor:3.19 platform stack as per the documentation, filling up database with default data and so on. The tax configuration is configured to be FLAT_RATES. When creating or querying for a checkout: checkout_shipping_price in calculations.py is called with the plugin manager. Down the call stack this plugin manager is passed to -> fetch_checkout_data -> _fetch_checkout_prices_if_expired. However there that plugin manager will not be used unless the tax configuration is set to TAX_APP.

### What did you expect to happen?

Shipping price calculation should be completely separated from tax calculations. Plugins should either be called by default or there should be an option provided to configure it. However best would be to simply allow it by default

### Environment

Saleor version: 3.19
OS and version: Mac idk

**Comment by korycins** [comment] 2024-07-08 12:38
Hey @supersilverlemonhaze,
`calculate_checkout_shipping` is dedicated to calculate the shipping price with taxes. This is why you need to change it to TAX_APP.
If you want to have a custom shipping price, you can use `get_shipping_methods_for_checkout` hook. It returns `ShippingMethodData`. This should allow you to provide custom shipping methods, with custom prices for checkout. Then you can turn off built-in Saleor's shipping methods, and use only the ones returned by your plugin. 

Instead of building a custom plugin, I would recommend creating a custom App. You can subscribe to the webhook event, and your app will receive a [sync](https://docs.saleor.io/docs/3.x/developer/extending/webhooks/synchronous-events/overview#introduction) webhook. Then your app can provide custom shipping methods ([docs](https://docs.saleor.io/docs/3.x/developer/extending/webhooks/synchronous-events/shipping#list-external-shipping-methods)) in the response.

**Comment by supersilverlemonhaze** [comment] 2024-07-10 05:37
Thanks for your response. After changing to TAX_APP the function is called
correctly. However interestingly despite my function returning the correct
amount of TaxedMoney for the shipping price in calculate_checkout_shipping
it is not reflected in the calculation of the total price... Any ideas?

**Comment by korycins** [comment] 2024-07-22 14:22
> Thanks for your response. After changing to TAX_APP the function is called
correctly. However interestingly despite my function returning the correct
amount of TaxedMoney for the shipping price in calculate_checkout_shipping
it is not reflected in the calculation of the total price... Any ideas?

I would say that this is because of you're using part of the tax interface. So for example when `PluginManager.calculate_checkout_total` doesn't have any plugin to call, it returns the default value which doesn't include your custom price.

**Comment by aniav** [comment] 2024-11-29 15:10
I will close the issue for now as it seems this is actually not a bug. Feel free to reopen if it keeps happening 🙌

**Closed by aniav** 2024-11-29 15:10 UTC
Labels: bug, triage
