### ISSUE TITLE
Gracefully handle checkout with empty stock

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#12938] opened 2023-05-25 09:34 UTC
## Problem

Many mutations like addressUpdate, addPromotCode fail when stock of one of the items is 0.

![image](https://github.com/saleor/saleor/assets/4006792/ab86bc2f-17bb-4d73-9bf0-d3e90ea49379)

This behavior is blocking users from interacting with checkout and could lead to bugs in the storefront.

### Porposal
Do not fail mutations and provide feedback if item stock is zero

**Comment by lkostrowski** [comment] 2023-10-02 10:50
@korycins @witoszekdev can you please propose a solution?

**Comment by lkostrowski** [comment] 2023-11-13 08:59
Probably will be implemented with https://github.com/saleor/saleor/issues/14580  

cc @korycins

**Comment by korycins** [comment] 2023-11-13 09:06
The specific scope defined in the issue is already covered by `Problems`:
https://docs.saleor.io/docs/3.x/developer/checkout/problems
We implemented there two "test" types: `CheckoutLineProblemInsufficientStock` and `CheckoutLineProblemVariantNotAvailable`.

**Comment by korycins** [comment] 2023-11-13 10:06
Closing, as the requested events are covered by `Problems`. 
Additionally, there is a task which covers extending `Problems` across the rest of the checkout problems & order: https://github.com/saleor/saleor/issues/14580

**Closed by korycins** 2023-11-13 10:06 UTC
Labels: feature request, checkout
