### ISSUE TITLE
User-facing mutation to add a note to their checkout

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#15029] opened 2023-12-14 13:36 UTC
## Problem

The checkout model has a `note` field that could theoretically allow the user to supply additional notes to their order. Real world use cases could be extra delivery instructions or food allergies. However, there does not appear to be any mutation that allows the user to add/edit the note.

---
### Mutations

```graphql
mutation checkoutNoteUpdate (note: "blah blah blah") {
  errors
  checkout
}
```

**Comment by timuric** [comment] 2024-01-02 16:54
Hey @khalibloo, alternatively you could try to use metadata

**Comment by khalibloo** [comment] 2024-01-02 16:57
Thanks @timuric. I considered that too, but I'm not sure if metadata gets carried over when a checkout is converted into an order. I want the information to be visible in the admin dashboard when the order is being processed.

**Comment by pitkes22** [comment] 2024-07-14 13:23
Duplicate of #9591

**Comment by maarcingebala** [comment] 2024-07-23 10:47
Fixed in https://github.com/saleor/saleor/pull/16315.

**Closed by maarcingebala** 2024-07-23 10:47 UTC
Labels: feature request, checkout

**Comment by timuric** [comment] 2024-07-23 12:36
Thank you for your contribution @pitkes22 !
