### ISSUE TITLE
Homepage is slow with large datasets

### ISSUE THREAD

**Issue by tomaszszymanski129** [saleor/saleor#13064] opened 2023-06-13 10:00 UTC
### What are you trying to achieve?

Optimize the homepage so it can be responsive even with the biggest datasets

### Steps to reproduce the problem

1. Have a large dataset
2. Open the homepage in the dashboard
3. Watch it takes ages to load

### What did you expect to happen?

The homepage shows the data with very little latency.

### Environment

Saleor version: any
OS and version: any

**Comment by tomaszszymanski129** [comment] 2023-06-20 10:31
Needs a decision, homepage itself will likely be removed as it's barely used and provides not useful data (but will require on Core to deprecate total_count fields maybe, but that's to be discussed)

**Comment by peteror** [comment] 2023-10-27 08:16
Some additional input if you don't mind - we use a metadata field to store the warehouse picker's id (so that everyone can see the orders assigned to them) - a query on the order table takes long too: 

Limit  (cost=326.97..32930.04 rows=100 width=2212) (actual time=3517.576..3517.584 rows=22 loops=1)
  Output: order_order.id, order_order.private_metadata, order_order.metadata, order_order.created, order_order.updated_at, order_order.status, order_order.user_id, order_order.language_code, order_order.tracking_client_id, order_order.billing_address_id, order_order.shipping_address_id, order_order.user_email, order_order.original_id, order_order.origin, order_order.currency, order_order.shipping_method_id, order_order.collection_point_id, order_order.shipping_method_name, order_order.collection_point_name, order_order.channel_id, order_order.shipping_price_net_amount, order_order.shipping_price_gross_amount, order_order.shipping_tax_rate, order_order.token, order_order.checkout_token, order_order.total_net_amount, order_order.undiscounted_total_net_amount, order_order.total_gross_amount, order_order.undiscounted_total_gross_amount, order_order.total_paid_amount, order_order.voucher_id, order_order.display_gross_prices, order_order.customer_note, order_order.weight, order_order.redirect_url, order_order.search_document
  Buffers: shared hit=214764
  ->  Incremental Sort  (cost=326.97..916799.28 rows=2811 width=2212) (actual time=3517.575..3517.581 rows=22 loops=1)
        Output: order_order.id, order_order.private_metadata, order_order.metadata, order_order.created, order_order.updated_at, order_order.status, order_order.user_id, order_order.language_code, order_order.tracking_client_id, order_order.billing_address_id, order_order.shipping_address_id, order_order.user_email, order_order.original_id, order_order.origin, order_order.currency, order_order.shipping_method_id, order_order.collection_point_id, order_order.shipping_method_name, order_order.collection_point_name, order_order.channel_id, order_order.shipping_price_net_amount, order_order.shipping_price_gross_amount, order_order.shipping_tax_rate, order_order.token, order_order.checkout_token, order_order.total_net_amount, order_order.undiscounted_total_net_amount, order_order.total_gross_amount, order_order.undiscounted_total_gross_amount, order_order.total_paid_amount, order_order.voucher_id, order_order.display_gross_prices, order_order.customer_note, order_order.weight, order_order.redirect_url, order_order.search_document
        Sort Key: order_order.created DESC, order_order.status DESC, order_order.id DESC
        Presorted Key: order_order.created
        Full-sort Groups: 1  Sort Method: quicksort  Average Memory: 64kB  Peak Memory: 64kB
        Buffers: shared hit=214764
        ->  Nested Loop  (cost=0.85..916672.78 rows=2811 width=2212) (actual time=0.331..3517.536 rows=22 loops=1)
              Output: order_order.id, order_order.private_metadata, order_order.metadata, order_order.created, order_order.updated_at, order_order.status, order_order.user_id, order_order.language_code, order_order.tracking_client_id, order_order.billing_address_id, order_order.shipping_address_id, order_order.user_email, order_order.original_id, order_order.origin, order_order.currency, order_order.shipping_method_id, order_order.collection_point_id, order_order.shipping_method_name, order_order.collection_point_name, order_order.channel_id, order_order.shipping_price_net_amount, order_order.shipping_price_gross_amount, order_order.shipping_tax_rate, order_order.token, order_order.checkout_token, order_order.total_net_amount, order_order.undiscounted_total_net_amount, order_order.total_gross_amount, order_order.undiscounted_total_gross_amount, order_order.total_paid_amount, order_order.voucher_id, order_order.display_gross_prices, order_order.customer_note, order_order.weight, order_order.redirect_url, order_order.search_document
              Buffers: shared hit=214764
              ->  Index Scan Backward using order_order_idx_created on public.order_order  (cost=0.43..894242.29 rows=2812 width=2212) (actual time=0.296..3517.321 rows=22 loops=1)
                    Output: order_order.id, order_order.created, order_order.tracking_client_id, order_order.user_email, order_order.token, order_order.billing_address_id, order_order.shipping_address_id, order_order.user_id, order_order.total_net_amount, order_order.voucher_id, order_order.language_code, order_order.shipping_price_gross_amount, order_order.total_gross_amount, order_order.shipping_price_net_amount, order_order.status, order_order.shipping_method_name, order_order.shipping_method_id, order_order.display_gross_prices, order_order.customer_note, order_order.weight, order_order.checkout_token, order_order.currency, order_order.metadata, order_order.private_metadata, order_order.channel_id, order_order.redirect_url, order_order.shipping_tax_rate, order_order.undiscounted_total_gross_amount, order_order.undiscounted_total_net_amount, order_order.total_paid_amount, order_order.origin, order_order.original_id, order_order.collection_point_id, order_order.collection_point_name, order_order.search_document, order_order.updated_at
"                    Filter: (((order_order.status)::text <> 'UNFULFILLED'::text) AND ((order_order.metadata ->> 'PickerId'::text) = 'VXNlcjoxMTIwMDE='::text) AND ((timezone('UTC'::text, order_order.created))::date >= '2023-10-25'::date))"
                    Rows Removed by Filter: 1723725
                    Buffers: shared hit=214670
              ->  Index Scan using payment_paymentmethod_order_id_58acb979 on public.payment_payment  (cost=0.43..7.97 rows=1 width=4) (actual time=0.007..0.008 rows=1 loops=22)
                    Output: payment_payment.id, payment_payment.gateway, payment_payment.is_active, payment_payment.created, payment_payment.modified, payment_payment.charge_status, payment_payment.billing_first_name, payment_payment.billing_last_name, payment_payment.billing_company_name, payment_payment.billing_address_1, payment_payment.billing_address_2, payment_payment.billing_city, payment_payment.billing_city_area, payment_payment.billing_postal_code, payment_payment.billing_country_code, payment_payment.billing_country_area, payment_payment.billing_email, payment_payment.customer_ip_address, payment_payment.cc_brand, payment_payment.cc_exp_month, payment_payment.cc_exp_year, payment_payment.cc_first_digits, payment_payment.cc_last_digits, payment_payment.extra_data, payment_payment.token, payment_payment.currency, payment_payment.total, payment_payment.captured_amount, payment_payment.checkout_id, payment_payment.order_id, payment_payment.to_confirm, payment_payment.payment_method_type, payment_payment.return_url, payment_payment.psp_reference, payment_payment.metadata, payment_payment.private_metadata, payment_payment.store_payment_method, payment_payment.partial
                    Index Cond: (payment_payment.order_id = order_order.id)
"                    Filter: (payment_payment.is_active AND ((payment_payment.charge_status)::text = ANY ('{partially-refunded,fully-charged}'::text[])))"
                    Buffers: shared hit=94
Planning:
  Buffers: shared hit=69
Planning Time: 0.749 ms
Execution Time: 3517.647 ms

(takes around 2 sec if I reduce the number of columns I need. The order_order table has about 1.7M records

**Comment by maarcingebala** [comment] 2023-10-31 15:06
Some time measures of these fields and traces:
- `productTopToday: reportProductSales(period: TODAY, first: 5, channel: $channel)` - took over 13s ([trace](https://app.datadoghq.com/apm/trace/3376253858773033780?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=12426392083252980023&spanViewType=metadata&timeHint=1698763257272.0908&view=spans))
- `ordersToFulfill: orders(filter: {status: READY_TO_FULFILL}, channel: $channel)` - 9.47s
- `ordersToCapture: orders(filter: {status: READY_TO_CAPTURE}, channel: $channel)` - 9.21s
- `activities: homepageEvents(last: 10)` - 5.07s ([trace](https://app.datadoghq.com/apm/trace/5862408476481607357?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=1439185328160213163&spanViewType=metadata&timeHint=1698763858746.475&view=spans))
- `salesToday: ordersTotal(period: TODAY, channel: $channel)` - 3.04s
- `ordersToday: orders(filter: {created: {gte: "2023-10-31", lte: "2023-10-31"}}, channel: $channel)` - 2.02s
- `productsOutOfStock: products(filter: {stockAvailability: OUT_OF_STOCK}, channel: $channel)` - 690ms

**Comment by maarcingebala** [comment] 2023-10-31 16:59
The following custom queries should be deprecated; they will be removed entirely in Saleor 4.0:
- `reportProductSales`
- `homepageEvents`
- `ordersTotal`

These should be optimized: `ordersToFulfill`, `ordersToCapture`, and `ordersToday` - these are using the regular `orders` query with filtering, which can be used in other parts of the dashboard as well, so it just needs to be faster.

**Comment by maarcingebala** [comment] 2023-11-22 06:45
Mentioned queries are now marked as deprecated. We also identified that the issue with dashboard queries being slow is caused by fetching `totalCount`. We should look into whether we can optimize totalCount, by that's a separate topic.

**Closed by maarcingebala** 2023-11-22 06:45 UTC
Labels: bug, performance, sre
